/*
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sogaard.jacob.Mdsdassignment2RuntimeModule;
import sogaard.jacob.Mdsdassignment2StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Mdsdassignment2IdeSetup extends Mdsdassignment2StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Mdsdassignment2RuntimeModule(), new Mdsdassignment2IdeModule()));
	}
	
}
