/*
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.ide;


/**
 * Use this class to register ide components.
 */
public class Mdsdassignment2IdeModule extends AbstractMdsdassignment2IdeModule {
}
