/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DslprojectUiModule extends AbstractDslprojectUiModule {

	public DslprojectUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
