/**
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.mdsdassignment2.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import sogaard.jacob.mdsdassignment2.ExpOp;
import sogaard.jacob.mdsdassignment2.Mdsdassignment2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Op</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpOpImpl extends MinimalEObjectImpl.Container implements ExpOp
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpOpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Mdsdassignment2Package.Literals.EXP_OP;
  }

} //ExpOpImpl
