/*
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Mdsdassignment2UiModule extends AbstractMdsdassignment2UiModule {

	public Mdsdassignment2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
