/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyMathSemanticSequencer;

@SuppressWarnings("all")
public class MyMathSemanticSequencer extends AbstractMyMathSemanticSequencer {
}
