/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.serializer;

import org.xtext.example.mydsl.serializer.AbstractMyMathSyntacticSequencer;

@SuppressWarnings("all")
public class MyMathSyntacticSequencer extends AbstractMyMathSyntacticSequencer {
}
