/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractMyMathIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyMathIdeModule extends AbstractMyMathIdeModule {
}
