/*
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Mdsdassignment2AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("sogaard/jacob/parser/antlr/internal/InternalMdsdassignment2.tokens");
	}
}
