/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MyMathStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyMathStandaloneSetup extends MyMathStandaloneSetupGenerated {
  public static void doSetup() {
    new MyMathStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
