/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.dslproject.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.dslproject.DslprojectPackage;
import org.xtext.example.dslproject.Question;
import org.xtext.example.dslproject.SuperQuestion;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Super Question</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dslproject.impl.SuperQuestionImpl#getSuperQuestion <em>Super Question</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SuperQuestionImpl extends MinimalEObjectImpl.Container implements SuperQuestion
{
  /**
   * The cached value of the '{@link #getSuperQuestion() <em>Super Question</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperQuestion()
   * @generated
   * @ordered
   */
  protected Question superQuestion;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuperQuestionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslprojectPackage.Literals.SUPER_QUESTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Question getSuperQuestion()
  {
    if (superQuestion != null && superQuestion.eIsProxy())
    {
      InternalEObject oldSuperQuestion = (InternalEObject)superQuestion;
      superQuestion = (Question)eResolveProxy(oldSuperQuestion);
      if (superQuestion != oldSuperQuestion)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DslprojectPackage.SUPER_QUESTION__SUPER_QUESTION, oldSuperQuestion, superQuestion));
      }
    }
    return superQuestion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Question basicGetSuperQuestion()
  {
    return superQuestion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuperQuestion(Question newSuperQuestion)
  {
    Question oldSuperQuestion = superQuestion;
    superQuestion = newSuperQuestion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DslprojectPackage.SUPER_QUESTION__SUPER_QUESTION, oldSuperQuestion, superQuestion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DslprojectPackage.SUPER_QUESTION__SUPER_QUESTION:
        if (resolve) return getSuperQuestion();
        return basicGetSuperQuestion();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DslprojectPackage.SUPER_QUESTION__SUPER_QUESTION:
        setSuperQuestion((Question)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DslprojectPackage.SUPER_QUESTION__SUPER_QUESTION:
        setSuperQuestion((Question)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DslprojectPackage.SUPER_QUESTION__SUPER_QUESTION:
        return superQuestion != null;
    }
    return super.eIsSet(featureID);
  }

} //SuperQuestionImpl
