/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.dslproject.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.dslproject.DslprojectPackage;
import org.xtext.example.dslproject.TrainingInput;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Training Input</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TrainingInputImpl extends MinimalEObjectImpl.Container implements TrainingInput
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TrainingInputImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DslprojectPackage.Literals.TRAINING_INPUT;
  }

} //TrainingInputImpl
