/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.dslproject;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.dslproject.DslprojectPackage#getAgent()
 * @model
 * @generated
 */
public interface Agent extends EObject
{
} // Agent
