/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.dslproject;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dslproject.Decl#getDeclarations <em>Declarations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dslproject.DslprojectPackage#getDecl()
 * @model
 * @generated
 */
public interface Decl extends TrainingInput
{
  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference.
   * @see #setDeclarations(Declaration)
   * @see org.xtext.example.dslproject.DslprojectPackage#getDecl_Declarations()
   * @model containment="true"
   * @generated
   */
  Declaration getDeclarations();

  /**
   * Sets the value of the '{@link org.xtext.example.dslproject.Decl#getDeclarations <em>Declarations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declarations</em>' containment reference.
   * @see #getDeclarations()
   * @generated
   */
  void setDeclarations(Declaration value);

} // Decl
