/**
 * generated by Xtext 2.20.0
 */
package org.xtext.example.dslproject;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.dslproject.TrainingRef#getInput <em>Input</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.dslproject.DslprojectPackage#getTrainingRef()
 * @model
 * @generated
 */
public interface TrainingRef extends EObject
{
  /**
   * Returns the value of the '<em><b>Input</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.dslproject.TrainingInput}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' containment reference list.
   * @see org.xtext.example.dslproject.DslprojectPackage#getTrainingRef_Input()
   * @model containment="true"
   * @generated
   */
  EList<TrainingInput> getInput();

} // TrainingRef
