/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.DslprojectRuntimeModule;
import org.xtext.example.DslprojectStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslprojectIdeSetup extends DslprojectStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslprojectRuntimeModule(), new DslprojectIdeModule()));
	}
	
}
