/*
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class Mdsdassignment2ProposalProvider extends AbstractMdsdassignment2ProposalProvider {
}
