/**
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.mdsdassignment2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Op</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sogaard.jacob.mdsdassignment2.Mdsdassignment2Package#getExpOp()
 * @model
 * @generated
 */
public interface ExpOp extends EObject
{
} // ExpOp
