/**
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.mdsdassignment2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Num</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sogaard.jacob.mdsdassignment2.Num#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see sogaard.jacob.mdsdassignment2.Mdsdassignment2Package#getNum()
 * @model
 * @generated
 */
public interface Num extends ExpOp
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see sogaard.jacob.mdsdassignment2.Mdsdassignment2Package#getNum_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link sogaard.jacob.mdsdassignment2.Num#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // Num
