/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.ide.contentassist.antlr.internal.InternalDslprojectParser;
import org.xtext.example.services.DslprojectGrammarAccess;

public class DslprojectParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslprojectGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslprojectGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getAgentAccess().getAlternatives(), "rule__Agent__Alternatives");
			builder.put(grammarAccess.getQuestionRefAccess().getAlternatives(), "rule__QuestionRef__Alternatives");
			builder.put(grammarAccess.getTrainingInputAccess().getAlternatives(), "rule__TrainingInput__Alternatives");
			builder.put(grammarAccess.getSysvariableAccess().getValueAlternatives_0(), "rule__Sysvariable__ValueAlternatives_0");
			builder.put(grammarAccess.getReferenceAccess().getAlternatives(), "rule__Reference__Alternatives");
			builder.put(grammarAccess.getIntentAccess().getGroup(), "rule__Intent__Group__0");
			builder.put(grammarAccess.getIntentAccess().getGroup_2(), "rule__Intent__Group_2__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getQuestionAccess().getGroup(), "rule__Question__Group__0");
			builder.put(grammarAccess.getSuperQuestionAccess().getGroup(), "rule__SuperQuestion__Group__0");
			builder.put(grammarAccess.getTrainingAccess().getGroup(), "rule__Training__Group__0");
			builder.put(grammarAccess.getTrainingRefAccess().getGroup(), "rule__TrainingRef__Group__0");
			builder.put(grammarAccess.getTrainingInputAccess().getGroup_0(), "rule__TrainingInput__Group_0__0");
			builder.put(grammarAccess.getTrainingInputAccess().getGroup_1(), "rule__TrainingInput__Group_1__0");
			builder.put(grammarAccess.getDeclarationAccess().getGroup(), "rule__Declaration__Group__0");
			builder.put(grammarAccess.getEntityExampleAccess().getGroup(), "rule__EntityExample__Group__0");
			builder.put(grammarAccess.getFollowRelationAccess().getGroup(), "rule__FollowRelation__Group__0");
			builder.put(grammarAccess.getModelAccess().getAgentAssignment(), "rule__Model__AgentAssignment");
			builder.put(grammarAccess.getIntentAccess().getNameAssignment_1(), "rule__Intent__NameAssignment_1");
			builder.put(grammarAccess.getIntentAccess().getZuperAssignment_2_1(), "rule__Intent__ZuperAssignment_2_1");
			builder.put(grammarAccess.getIntentAccess().getQuestionAssignment_3(), "rule__Intent__QuestionAssignment_3");
			builder.put(grammarAccess.getIntentAccess().getTrainingAssignment_4(), "rule__Intent__TrainingAssignment_4");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getEntityAccess().getExampleAssignment_3(), "rule__Entity__ExampleAssignment_3");
			builder.put(grammarAccess.getQuestionRefAccess().getQuestionAssignment_0(), "rule__QuestionRef__QuestionAssignment_0");
			builder.put(grammarAccess.getQuestionRefAccess().getSuperQuestionAssignment_1(), "rule__QuestionRef__SuperQuestionAssignment_1");
			builder.put(grammarAccess.getQuestionAccess().getRequiredAssignment_0(), "rule__Question__RequiredAssignment_0");
			builder.put(grammarAccess.getQuestionAccess().getNameAssignment_1(), "rule__Question__NameAssignment_1");
			builder.put(grammarAccess.getQuestionAccess().getQuestionEntityAssignment_3(), "rule__Question__QuestionEntityAssignment_3");
			builder.put(grammarAccess.getQuestionAccess().getPromptAssignment_5(), "rule__Question__PromptAssignment_5");
			builder.put(grammarAccess.getSuperQuestionAccess().getSuperQuestionAssignment_1(), "rule__SuperQuestion__SuperQuestionAssignment_1");
			builder.put(grammarAccess.getQuestionEntityAccess().getWithEntityAssignment(), "rule__QuestionEntity__WithEntityAssignment");
			builder.put(grammarAccess.getTrainingAccess().getTrainingrefAssignment_2(), "rule__Training__TrainingrefAssignment_2");
			builder.put(grammarAccess.getTrainingRefAccess().getInputAssignment_0(), "rule__TrainingRef__InputAssignment_0");
			builder.put(grammarAccess.getTrainingInputAccess().getSAssignment_0_1(), "rule__TrainingInput__SAssignment_0_1");
			builder.put(grammarAccess.getTrainingInputAccess().getDeclarationsAssignment_1_1(), "rule__TrainingInput__DeclarationsAssignment_1_1");
			builder.put(grammarAccess.getDeclarationAccess().getTrainingstringAssignment_1(), "rule__Declaration__TrainingstringAssignment_1");
			builder.put(grammarAccess.getDeclarationAccess().getReferenceAssignment_3(), "rule__Declaration__ReferenceAssignment_3");
			builder.put(grammarAccess.getEntityExampleAccess().getNameAssignment_0(), "rule__EntityExample__NameAssignment_0");
			builder.put(grammarAccess.getSysvariableAccess().getValueAssignment(), "rule__Sysvariable__ValueAssignment");
			builder.put(grammarAccess.getReferenceAccess().getEntityAssignment_0(), "rule__Reference__EntityAssignment_0");
			builder.put(grammarAccess.getReferenceAccess().getSysvarAssignment_1(), "rule__Reference__SysvarAssignment_1");
			builder.put(grammarAccess.getFollowRelationAccess().getParentAssignment_1(), "rule__FollowRelation__ParentAssignment_1");
			builder.put(grammarAccess.getFollowRelationAccess().getChildAssignment_3(), "rule__FollowRelation__ChildAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslprojectGrammarAccess grammarAccess;

	@Override
	protected InternalDslprojectParser createParser() {
		InternalDslprojectParser result = new InternalDslprojectParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslprojectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslprojectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
