/*
 * generated by Xtext 2.20.0
 */
package sogaard.jacob.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMdsdassignment2ScopeProvider extends DelegatingScopeProvider {
}
