/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.parser.antlr.internal.InternalDslprojectParser;
import org.xtext.example.services.DslprojectGrammarAccess;

public class DslprojectParser extends AbstractAntlrParser {

	@Inject
	private DslprojectGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDslprojectParser createParser(XtextTokenStream stream) {
		return new InternalDslprojectParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DslprojectGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslprojectGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
