/*
 * generated by Xtext 2.20.0
 */
package org.xtext.example.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslprojectScopeProvider extends DelegatingScopeProvider {
}
